### PR TITLE
Komodo 9 skin update

### PR DESCRIPTION
**Pull request by Defman21**
I did some changes to make the skin looks better on Linux.

### CODE REVIEW

**Comment by Defman21** [comment]
Also I removed Komodo 8 support.

**Comment by Naatan** [comment]
Thanks Defman. Why did you change the font-weight though? It was meant to be a subtle difference. Font-weight 700 is too heavy in my opinion.

**Comment by Defman21** [comment]
Because the fonts looks too light on Linux

**Comment by Defman21** [comment]
But I'll play around with the font-weight.

**Comment by Naatan** [comment]
Alternatively, try doing something like this:

https://github.com/Komodo/KomodoEdit/blob/master/src/modules/abyss_skin/content/manifest/chrome.manifest#L27

Ie. use heavier font weight on Linux, but not on OSX/Windows.

With your current changes the fonts would be very thick on OSX, which is also not desirable.

**Pull request merged**
